config/routes.rb
Rails.application.routes.draw do
root 'users#index'
get '/sign_in', to: 'sessions#new'
post '/sign_in', to: 'sessions#create'
delete '/sign_out', to: 'sessions#destroy'
resources :users, only: [:new, :create, :show, :index]
resources :events, only: [:index, :new, :create, :show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :host, class_name: "User", foreign_key: "host_id"
  has_many :invitations, foreign_key: "event_id", dependent: :destroy
  has_many :guests, through: :invitations, source: :guest

  scope :previous, ->{ where("date < ?", Time.zone.now) }
  scope :upcoming, ->{ where("date >= ?", Time.zone.now) }
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :guest, class_name: "User", foreign_key: "guest_id"
  belongs_to :attended_event, class_name: "Event", foreign_key: "event_id"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, foreign_key: 'host_id', dependent: :destroy
  has_many :invitations, foreign_key: "guest_id", dependent: :destroy
  has_many :attended_events, through: :invitations, source: :attended_event

  #Authentification method
  def authenticate(password)
    password == self.password
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @prevoius_events = Event.prevoius
    @upcoming_events = Event.upcoming
  end

  def new
    @event = current_user.events.build
  end

  def show
    @event = Event.find(params[:id])
    @users = @event.guests
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      flash[:success] = "New event created!"
      redirect_to @event
    else
      render 'new'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to root_url
  end

  private

    def event_params
      params.require(:event).permit(:location, :date)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      sign_in(@user)
      flash[:success] = "User signed in!"
      redirect_to @user
    else
      flash.now[:warning] = "Incorrect email or password!"
      render 'new'
    end
  end

  def destroy
    sign_out if signed_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "User created!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @upcoming_events = @user.events.upcoming
    @upcoming_attended_events = @user.attended_events.upcoming
    @previous_events = @user.events.previous
    @previous_attended_events = @user.attended_events.previous
  end

  def index
    @users = User.all
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    if user_id = cookies[:user_id]
      @current_user ||= User.find_by(id: user_id)
    end
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_in(user)
    cookies.permanent[:user_id] = user.id
  end

  def sign_out
    @current_user = nil
    cookies.delete(:user_id)
  end

end

app/views/events/_event.html.erb
<li>
  <%= link_to "#{event.location}", event_path(event) %>
  <%= " - #{event.date} - Host: " %>
  <%= link_to event.host.name, user_path(event.host) %>
  <% if current_user.id == event.host.id %>
    <%= link_to "Delete", event_path(event), method: :delete, data: { confirm: "Are you sure you wnat to delete this event?"} %>
  <% end %>
</li>

app/views/events/_event_form.html.erb
<%= form_for @event do |f| %>
  <%= f.label "Location:" %><br />
  <%= f.text_field :location %><br />

  <%= f.label "Date:" %><br />
  <%= f.date_field :date %><br />

  <%= f.submit "Create event" %><br />
<% end %>

app/views/events/index.html.erb
<h1>Upcoming Events: </h1>

<ol>
  <%= render @upcoming_events %>
</ol>

<h1>Previous Events: </h1>

<ol>
  <%= render @previous_events %>
</ol>

app/views/events/new.html.erb
<h1>Create new event:</h1>

<%= render 'event_form' %>

app/views/events/show.html.erb
<h1>Event: <%= @event.id %></h1>

<%= "#{@event.location} - #{@event.date} - Host: " %>
<%= link_to @event.host.name, user_path(@event.host) %>
<%= link_to "Delete", event_path(@event), method: :delete, data: { confirm: "Are you sure you wnat to delete this event?"} %>
<br />
<hr />
<%= @event.description %>

<h2>Guests: </h2>
<ol>
  <%= render @users %>
</ol>

app/views/layouts/_header.html.erb
<header>
  <%= link_to "Users", users_path %>
  <%= link_to "Events", events_path %>
  <% if signed_in? %>
    <%= link_to "New Event", new_event_path %>
    <%= link_to "Sign Out", sign_out_path, method: :delete %>
    <br />
    Signed In As: <%= link_to current_user.name, user_path(current_user) %>
  <% else %>
    <%= link_to "Sign Up", new_user_path %>
    <%= link_to "Sign In", sign_in_path %>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Private Events App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/flash' %>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if flash.any? %>
  <div class="flash">
    <% flash.each do |key, message| %>
      <%= message %>
    <% end %>
  </div>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= link_to "#{user.name} (#{user.events.count})", user_path(user) %>
</li>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>Users: </h1>
<ol>
  <%= render @users %>
</ol>

app/views/users/new.html.erb
<h1>Create new user</h1>

<%= form_for @user do |f| %>
  <%= f.label "Email:" %><br />
  <%= f.email_field :email %><br />

  <%= f.label "Name:" %><br />
  <%= f.text_field :name %><br />

  <%= f.label "Password:" %><br />
  <%= f.password_field :password %><br />

  <%= f.submit "Create" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<div class="user_events">
  <h3>Hosted Events:</h3>
  <h3>Upcoming: </h3>
  <ol>
    <%= render @upcoming_events %>
  </ol>

  <h3>Prevoius: </h3>
  <ol>
    <%= render @previous_events %>
  </ol>
</div>

<h3>Attended Events: </h3>
<h3>Upcoming: </h3>
<ol>
  <%= render @upcoming_attended_events %>
</ol>

<h3>Prevoius: </h3>
<ol>
  <%= render @previous_attended_events %>
</ol>